[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules", "lib"]
via_ir = true


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
flare = "${FLARE_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }







# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
